In [1]:
# Import requirements

import pandas as pd

In [2]:
# Load in catalog dataframe
catalog = pd.read_csv('../data/processed_catalog.csv')

In [3]:
display(catalog)

,year,month,day,hour,minute,second,lat,lon,dep,eh1,eh2,az,ez,mag,id,month_num,day_num,date
0,2014,11,4,20,46,1.620,45.93439,-130.02092,1.148,0.432,0.023,168,0.030,1.5,1000002,11,4,2014-11-01
1,2014,11,4,22,12,40.197,45.92662,-130.01597,0.904,0.089,0.027,114,0.039,0.2,1000010,11,4,2014-11-01
2,2014,11,4,22,41,7.813,45.92568,-129.98059,0.821,0.016,0.000,146,0.003,0.4,1000012,11,4,2014-11-01
3,2014,11,5,0,43,9.964,45.94480,-129.99482,1.140,0.222,0.030,87,0.698,-0.0,1000025,11,5,2014-11-01
4,2014,11,5,1,3,48.101,45.93533,-129.98498,0.559,-1.000,-1.000,-1,-1.000,-0.1,1000030,11,5,2014-11-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
144323,2021,12,27,17,3,40.440,45.94228,-130.01324,0.463,0.015,0.007,86,0.005,0.3,1501597,12,27,2021-12-01
144324,2021,12,27,19,51,32.350,45.93447,-130.01936,1.230,0.020,0.010,42,0.008,0.7,1501600,12,27,2021-12-01
144325,2021,12,28,2,33,58.284,45.95371,-129.99781,0.436,0.137,0.008,9,0.014,0.3,1501602,12,28,2021-12-01
144326,2021,12,29,0,9,14.414,45.94125,-130.02061,1.005,0.021,0.007,74,0.009,1.2,1501617,12,29,2021-12-01
144327,2021,12,30,17,19,12.659,45.93954,-130.01069,0.480,0.028,0.008,24,0.010,0.3,1501635,12,30,2021-12-01

In [18]:
# Format the date_time column using existing columns
catalog['date_time'] = catalog.apply(
    lambda row: f"{row['year']}-{row['month']:02d}-{row['day']:02d}T{row['hour']:02d}:{row['minute']:02d}:{row['second']:04.1f}Z", 
    axis=1
)

# Display the first few rows to verify the formatting
print(catalog[['year', 'month', 'day', 'hour', 'minute', 'second', 'date_time']].head())

   year  month  day  hour  minute  second               date_time
0  2014     11    4    20      46   1.620  2014-11-04T20:46:01.6Z
1  2014     11    4    22      12  40.197  2014-11-04T22:12:40.2Z
2  2014     11    4    22      41   7.813  2014-11-04T22:41:07.8Z
3  2014     11    5     0      43   9.964  2014-11-05T00:43:10.0Z
4  2014     11    5     1       3  48.101  2014-11-05T01:03:48.1Z

In [19]:
# Convert date_time to datetime format
catalog['datetime_obj'] = pd.to_datetime(catalog['date_time'])

# Add 20 seconds to create end_time
catalog['datetime_end'] = catalog['datetime_obj'] + pd.Timedelta(seconds=20)

# Format the end_time in the same format as date_time
catalog['end_time'] = catalog['datetime_end'].dt.strftime('%Y-%m-%dT%H:%M:%S.%fZ').str[:-5] + 'Z'

# Clean up temporary columns
catalog = catalog.drop(['datetime_obj', 'datetime_end'], axis=1)

# Display the first few rows to verify the formatting
print(catalog[['date_time', 'end_time']].head())

                date_time                 end_time
0  2014-11-04T20:46:01.6Z  2014-11-04T20:46:21.60Z
1  2014-11-04T22:12:40.2Z  2014-11-04T22:13:00.20Z
2  2014-11-04T22:41:07.8Z  2014-11-04T22:41:27.80Z
3  2014-11-05T00:43:10.0Z  2014-11-05T00:43:30.00Z
4  2014-11-05T01:03:48.1Z  2014-11-05T01:04:08.10Z

In [20]:
display(catalog)

,year,month,day,hour,minute,second,lat,lon,dep,eh1,eh2,az,ez,mag,id,month_num,day_num,date,date_time,end_time
0,2014,11,4,20,46,1.620,45.93439,-130.02092,1.148,0.432,0.023,168,0.030,1.5,1000002,11,4,2014-11-01,2014-11-04T20:46:01.6Z,2014-11-04T20:46:21.60Z
1,2014,11,4,22,12,40.197,45.92662,-130.01597,0.904,0.089,0.027,114,0.039,0.2,1000010,11,4,2014-11-01,2014-11-04T22:12:40.2Z,2014-11-04T22:13:00.20Z
2,2014,11,4,22,41,7.813,45.92568,-129.98059,0.821,0.016,0.000,146,0.003,0.4,1000012,11,4,2014-11-01,2014-11-04T22:41:07.8Z,2014-11-04T22:41:27.80Z
3,2014,11,5,0,43,9.964,45.94480,-129.99482,1.140,0.222,0.030,87,0.698,-0.0,1000025,11,5,2014-11-01,2014-11-05T00:43:10.0Z,2014-11-05T00:43:30.00Z
4,2014,11,5,1,3,48.101,45.93533,-129.98498,0.559,-1.000,-1.000,-1,-1.000,-0.1,1000030,11,5,2014-11-01,2014-11-05T01:03:48.1Z,2014-11-05T01:04:08.10Z
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
144323,2021,12,27,17,3,40.440,45.94228,-130.01324,0.463,0.015,0.007,86,0.005,0.3,1501597,12,27,2021-12-01,2021-12-27T17:03:40.4Z,2021-12-27T17:04:00.40Z
144324,2021,12,27,19,51,32.350,45.93447,-130.01936,1.230,0.020,0.010,42,0.008,0.7,1501600,12,27,2021-12-01,2021-12-27T19:51:32.4Z,2021-12-27T19:51:52.40Z
144325,2021,12,28,2,33,58.284,45.95371,-129.99781,0.436,0.137,0.008,9,0.014,0.3,1501602,12,28,2021-12-01,2021-12-28T02:33:58.3Z,2021-12-28T02:34:18.30Z
144326,2021,12,29,0,9,14.414,45.94125,-130.02061,1.005,0.021,0.007,74,0.009,1.2,1501617,12,29,2021-12-01,2021-12-29T00:09:14.4Z,2021-12-29T00:09:34.40Z
144327,2021,12,30,17,19,12.659,45.93954,-130.01069,0.480,0.028,0.008,24,0.010,0.3,1501635,12,30,2021-12-01,2021-12-30T17:19:12.7Z,2021-12-30T17:19:32.70Z

In [21]:
# date_time and end_time are now in the correct format for ObsPy and get_trace function.

# save the updated catalog to a CSV file
catalog.to_csv('../data/processed_catalog_date_time.csv', index=False)

In [22]:
# Save the first 5000 events to a CSV file
catalog.head(5000).to_csv('../data/processed_catalog_date_time_5000.csv', index=False)

In [23]:
# Save the first 10 events to a CSV file for testing
catalog.head(10).to_csv('../data/processed_catalog_date_time_10.csv', index=False)

In [24]:
# Load test catalog
test_catalog = pd.read_csv('../data/processed_catalog_date_time_10.csv')

In [25]:
display(test_catalog)

,year,month,day,hour,minute,second,lat,lon,dep,eh1,eh2,az,ez,mag,id,month_num,day_num,date,date_time,end_time
0,2014,11,4,20,46,1.620,45.93439,-130.02092,1.148,0.432,0.023,168,0.030,1.5,1000002,11,4,2014-11-01,2014-11-04T20:46:01.6Z,2014-11-04T20:46:21.60Z
1,2014,11,4,22,12,40.197,45.92662,-130.01597,0.904,0.089,0.027,114,0.039,0.2,1000010,11,4,2014-11-01,2014-11-04T22:12:40.2Z,2014-11-04T22:13:00.20Z
2,2014,11,4,22,41,7.813,45.92568,-129.98059,0.821,0.016,0.000,146,0.003,0.4,1000012,11,4,2014-11-01,2014-11-04T22:41:07.8Z,2014-11-04T22:41:27.80Z
3,2014,11,5,0,43,9.964,45.94480,-129.99482,1.140,0.222,0.030,87,0.698,-0.0,1000025,11,5,2014-11-01,2014-11-05T00:43:10.0Z,2014-11-05T00:43:30.00Z
4,2014,11,5,1,3,48.101,45.93533,-129.98498,0.559,-1.000,-1.000,-1,-1.000,-0.1,1000030,11,5,2014-11-01,2014-11-05T01:03:48.1Z,2014-11-05T01:04:08.10Z
5,2014,11,5,1,4,0.989,45.92855,-129.97997,0.871,0.159,0.026,57,0.157,0.1,1000031,11,5,2014-11-01,2014-11-05T01:04:01.0Z,2014-11-05T01:04:21.00Z
6,2014,11,5,1,4,43.594,45.92895,-129.98158,0.484,0.033,0.019,93,0.039,0.1,1000032,11,5,2014-11-01,2014-11-05T01:04:43.6Z,2014-11-05T01:05:03.60Z
7,2014,11,5,1,5,6.950,45.93262,-129.98623,0.080,3.422,0.022,36,0.834,-0.1,1000033,11,5,2014-11-01,2014-11-05T01:05:07.0Z,2014-11-05T01:05:27.00Z
8,2014,11,6,0,9,13.803,45.92904,-130.00189,0.903,0.047,0.009,115,0.019,0.5,1000067,11,6,2014-11-01,2014-11-06T00:09:13.8Z,2014-11-06T00:09:33.80Z
9,2014,11,6,0,9,37.960,45.98058,-130.02578,4.675,-1.000,-1.000,-1,-1.000,0.7,1000068,11,6,2014-11-01,2014-11-06T00:09:38.0Z,2014-11-06T00:09:58.00Z