In [1]:
import obspy
import pickle
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import swspy

OMP: Info #276: omp_set_nested routine deprecated, please use omp_set_max_active_levels instead.

In [18]:
catalog = pd.read_csv('../data/final_catalog.csv')

In [20]:
display(catalog)

,Unnamed: 0,catalog_idx,catalog_id,catalog_year,catalog_month,catalog_day,catalog_hour,catalog_minute,catalog_second,catalog_datetime,...,phase_event_id,time_diff_seconds,has_data,total_picks,p_arrival_time,p_weight,p_quality,s_arrival_time,s_weight,s_quality
0,0,0.0,1000002,2014,11,4,20,46,1.620,2014-11-04 20:46:01.620,...,1000002.0,0.350,True,2,0.00,NaN,EH,0.22,-0.2,EH
1,1,0.0,1000002,2014,11,4,20,46,1.620,2014-11-04 20:46:01.620,...,1000002.0,0.350,True,2,0.50,1.0,EH,1.28,1.0,EH
2,2,0.0,1000002,2014,11,4,20,46,1.620,2014-11-04 20:46:01.620,...,1000002.0,0.350,True,2,1.52,1.0,HH,2.27,1.0,HH
3,3,0.0,1000002,2014,11,4,20,46,1.620,2014-11-04 20:46:01.620,...,1000002.0,0.350,True,2,0.23,NaN,EH,0.85,-0.2,EH
4,4,0.0,1000002,2014,11,4,20,46,1.620,2014-11-04 20:46:01.620,...,1000002.0,0.350,False,0,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1010277,1010277,144327.0,1501635,2021,12,30,17,19,12.659,2021-12-30 17:19:12.659,...,1501635.0,0.009,True,1,NaN,NaN,NaN,1.58,1.0,HH
1010278,1010278,144327.0,1501635,2021,12,30,17,19,12.659,2021-12-30 17:19:12.659,...,1501635.0,0.009,True,2,0.49,1.0,EH,1.05,NaN,EH
1010279,1010279,144327.0,1501635,2021,12,30,17,19,12.659,2021-12-30 17:19:12.659,...,1501635.0,0.009,False,0,NaN,NaN,NaN,NaN,NaN,NaN
1010280,1010280,144327.0,1501635,2021,12,30,17,19,12.659,2021-12-30 17:19:12.659,...,1501635.0,0.009,True,2,1.30,0.2,EH,1.58,NaN,EH
1010281,1010281,144327.0,1501635,2021,12,30,17,19,12.659,2021-12-30 17:19:12.659,...,1501635.0,0.009,False,0,NaN,NaN,NaN,NaN,NaN,NaN

In [21]:
catalog = catalog.drop(['Unnamed: 0', 'catalog_idx', 'catalog_month', 'catalog_day', 'catalog_hour','catalog_minute', 'catalog_second', 'phase_event_id'], axis=1)

In [22]:
display(catalog)

,catalog_id,catalog_year,catalog_datetime,catalog_lat,catalog_lon,catalog_depth,catalog_mag,station,time_diff_seconds,has_data,total_picks,p_arrival_time,p_weight,p_quality,s_arrival_time,s_weight,s_quality
0,1000002,2014,2014-11-04 20:46:01.620,45.93439,-130.02092,1.148,1.5,OOAXAS2,0.350,True,2,0.00,NaN,EH,0.22,-0.2,EH
1,1000002,2014,2014-11-04 20:46:01.620,45.93439,-130.02092,1.148,1.5,OOAXEC3,0.350,True,2,0.50,1.0,EH,1.28,1.0,EH
2,1000002,2014,2014-11-04 20:46:01.620,45.93439,-130.02092,1.148,1.5,OOAXEC2,0.350,True,2,1.52,1.0,HH,2.27,1.0,HH
3,1000002,2014,2014-11-04 20:46:01.620,45.93439,-130.02092,1.148,1.5,OOAXAS1,0.350,True,2,0.23,NaN,EH,0.85,-0.2,EH
4,1000002,2014,2014-11-04 20:46:01.620,45.93439,-130.02092,1.148,1.5,OOAXCC1,0.350,False,0,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1010277,1501635,2021,2021-12-30 17:19:12.659,45.93954,-130.01069,0.480,0.3,OOAXEC2,0.009,True,1,NaN,NaN,NaN,1.58,1.0,HH
1010278,1501635,2021,2021-12-30 17:19:12.659,45.93954,-130.01069,0.480,0.3,OOAXAS1,0.009,True,2,0.49,1.0,EH,1.05,NaN,EH
1010279,1501635,2021,2021-12-30 17:19:12.659,45.93954,-130.01069,0.480,0.3,OOAXCC1,0.009,False,0,NaN,NaN,NaN,NaN,NaN,NaN
1010280,1501635,2021,2021-12-30 17:19:12.659,45.93954,-130.01069,0.480,0.3,OOAXEC1,0.009,True,2,1.30,0.2,EH,1.58,NaN,EH
1010281,1501635,2021,2021-12-30 17:19:12.659,45.93954,-130.01069,0.480,0.3,OOAXID1,0.009,False,0,NaN,NaN,NaN,NaN,NaN,NaN

In [24]:
catalog = catalog.dropna(ignore_index = True)

In [25]:
catalog = catalog.drop('has_data', axis=1)

In [27]:
display(catalog)

,catalog_id,catalog_year,catalog_datetime,catalog_lat,catalog_lon,catalog_depth,catalog_mag,station,time_diff_seconds,total_picks,p_arrival_time,p_weight,p_quality,s_arrival_time,s_weight,s_quality
0,1000002,2014,2014-11-04 20:46:01.620,45.93439,-130.02092,1.148,1.5,OOAXEC3,0.350,2,0.50,1.0,EH,1.28,1.0,EH
1,1000002,2014,2014-11-04 20:46:01.620,45.93439,-130.02092,1.148,1.5,OOAXEC2,0.350,2,1.52,1.0,HH,2.27,1.0,HH
2,1000010,2014,2014-11-04 22:12:40.197,45.92662,-130.01597,0.904,0.2,OOAXEC3,0.033,2,0.82,1.0,EH,1.54,1.0,EH
3,1000033,2014,2014-11-05 01:05:06.950,45.93262,-129.98623,0.080,-0.1,OOAXAS1,0.200,2,0.27,-0.2,EH,0.95,-0.5,EH
4,1000067,2014,2014-11-06 00:09:13.803,45.92904,-130.00189,0.903,0.5,OOAXAS2,1.543,2,1.71,-0.5,EH,2.99,-0.2,EH
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
311428,1501617,2021,2021-12-29 00:09:14.414,45.94125,-130.02061,1.005,1.2,OOAXEC2,0.054,2,0.93,1.0,HH,1.74,1.0,HH
311429,1501617,2021,2021-12-29 00:09:14.414,45.94125,-130.02061,1.005,1.2,OOAXAS1,0.054,2,0.65,1.0,EH,1.34,1.0,EH
311430,1501617,2021,2021-12-29 00:09:14.414,45.94125,-130.02061,1.005,1.2,OOAXCC1,0.054,2,0.60,1.0,HH,1.19,0.5,HH
311431,1501617,2021,2021-12-29 00:09:14.414,45.94125,-130.02061,1.005,1.2,OOAXEC1,0.054,2,0.86,1.0,EH,1.60,1.0,EH
311432,1501617,2021,2021-12-29 00:09:14.414,45.94125,-130.02061,1.005,1.2,OOAXID1,0.054,2,0.97,1.0,EH,1.64,1.0,EH

In [37]:
# Check column names
print("Current column names:")
print(catalog.columns.tolist())

Current column names:
['catalog_id', 'catalog_year', 'catalog_datetime', 'catalog_lat', 'catalog_lon', 'catalog_depth', 'catalog_mag', 'station', 'time_diff_seconds', 'total_picks', 'p_arrival_time', 'p_weight', 'p_quality', 's_arrival_time', 's_weight', 's_quality']

In [29]:
# Create a new dataframe with renamed columns (remove "catalog_" prefix)
catalog_renamed = catalog.copy()

# Create a mapping dictionary to rename columns
column_mapping = {}
for col in catalog_renamed.columns:
    if col.startswith('catalog_'):
        # Remove "catalog_" prefix
        new_name = col.replace('catalog_', '')
        column_mapping[col] = new_name

print("Column renaming mapping:")
for old_name, new_name in column_mapping.items():
    print(f"'{old_name}' -> '{new_name}'")

# Apply the renaming
catalog_renamed = catalog_renamed.rename(columns=column_mapping)

print(f"\nNew column names:")
print(catalog_renamed.columns.tolist())

Column renaming mapping:
'catalog_id' -> 'id'
'catalog_year' -> 'year'
'catalog_datetime' -> 'datetime'
'catalog_lat' -> 'lat'
'catalog_lon' -> 'lon'
'catalog_depth' -> 'depth'
'catalog_mag' -> 'mag'

New column names:
['id', 'year', 'datetime', 'lat', 'lon', 'depth', 'mag', 'station', 'time_diff_seconds', 'total_picks', 'p_arrival_time', 'p_weight', 'p_quality', 's_arrival_time', 's_weight', 's_quality']

In [30]:
# Display the new dataframe with renamed columns
print("New dataframe 'catalog_renamed' with cleaned column names:")
display(catalog_renamed)

New dataframe 'catalog_renamed' with cleaned column names:

,id,year,datetime,lat,lon,depth,mag,station,time_diff_seconds,total_picks,p_arrival_time,p_weight,p_quality,s_arrival_time,s_weight,s_quality
0,1000002,2014,2014-11-04 20:46:01.620,45.93439,-130.02092,1.148,1.5,OOAXEC3,0.350,2,0.50,1.0,EH,1.28,1.0,EH
1,1000002,2014,2014-11-04 20:46:01.620,45.93439,-130.02092,1.148,1.5,OOAXEC2,0.350,2,1.52,1.0,HH,2.27,1.0,HH
2,1000010,2014,2014-11-04 22:12:40.197,45.92662,-130.01597,0.904,0.2,OOAXEC3,0.033,2,0.82,1.0,EH,1.54,1.0,EH
3,1000033,2014,2014-11-05 01:05:06.950,45.93262,-129.98623,0.080,-0.1,OOAXAS1,0.200,2,0.27,-0.2,EH,0.95,-0.5,EH
4,1000067,2014,2014-11-06 00:09:13.803,45.92904,-130.00189,0.903,0.5,OOAXAS2,1.543,2,1.71,-0.5,EH,2.99,-0.2,EH
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
311428,1501617,2021,2021-12-29 00:09:14.414,45.94125,-130.02061,1.005,1.2,OOAXEC2,0.054,2,0.93,1.0,HH,1.74,1.0,HH
311429,1501617,2021,2021-12-29 00:09:14.414,45.94125,-130.02061,1.005,1.2,OOAXAS1,0.054,2,0.65,1.0,EH,1.34,1.0,EH
311430,1501617,2021,2021-12-29 00:09:14.414,45.94125,-130.02061,1.005,1.2,OOAXCC1,0.054,2,0.60,1.0,HH,1.19,0.5,HH
311431,1501617,2021,2021-12-29 00:09:14.414,45.94125,-130.02061,1.005,1.2,OOAXEC1,0.054,2,0.86,1.0,EH,1.60,1.0,EH
311432,1501617,2021,2021-12-29 00:09:14.414,45.94125,-130.02061,1.005,1.2,OOAXID1,0.054,2,0.97,1.0,EH,1.64,1.0,EH

In [32]:
# Filter out earthquakes from year 2014
print(f"Original dataframe shape: {catalog_renamed.shape}")
print(f"Number of earthquakes from 2014: {(catalog_renamed['year'] == 2014).sum()}")

# Create filtered dataframe excluding year 2014
catalog_filtered = catalog_renamed[catalog_renamed['year'] != 2014].copy()

print(f"Filtered dataframe shape: {catalog_filtered.shape}")
print(f"Earthquakes removed: {catalog_renamed.shape[0] - catalog_filtered.shape[0]}")

# Check the year range in the filtered data
print(f"\nYear range in filtered data: {catalog_filtered['year'].min()} to {catalog_filtered['year'].max()}")
print(f"Unique years: {sorted(catalog_filtered['year'].unique())}")

Original dataframe shape: (311433, 16)
Number of earthquakes from 2014: 9554
Filtered dataframe shape: (301879, 16)
Earthquakes removed: 9554

Year range in filtered data: 2015 to 2021
Unique years: [np.int64(2015), np.int64(2016), np.int64(2017), np.int64(2018), np.int64(2019), np.int64(2020), np.int64(2021)]

In [33]:
display(catalog_filtered)

,id,year,datetime,lat,lon,depth,mag,station,time_diff_seconds,total_picks,p_arrival_time,p_weight,p_quality,s_arrival_time,s_weight,s_quality
9554,1015287,2015,2015-01-01 00:03:39.175,45.93845,-129.96648,0.099,1.0,OOAXEC3,0.085,2,0.58,1.0,EH,1.35,0.5,EH
9555,1015291,2015,2015-01-01 01:30:03.214,45.92372,-129.98706,1.109,0.3,OOAXEC3,0.004,2,0.52,1.0,EH,1.03,1.0,EH
9556,1015293,2015,2015-01-01 01:52:44.889,45.92534,-129.96973,1.503,0.2,OOAXAS1,0.099,2,-1.12,0.2,EH,1.59,0.5,EH
9557,1015298,2015,2015-01-01 02:54:51.020,45.98200,-130.01392,0.958,0.6,OOAXEC3,0.160,2,1.48,0.5,EH,2.82,1.0,EH
9558,1015298,2015,2015-01-01 02:54:51.020,45.98200,-130.01392,0.958,0.6,OOAXEC2,0.160,2,0.73,1.0,HH,1.62,0.2,HH
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
311428,1501617,2021,2021-12-29 00:09:14.414,45.94125,-130.02061,1.005,1.2,OOAXEC2,0.054,2,0.93,1.0,HH,1.74,1.0,HH
311429,1501617,2021,2021-12-29 00:09:14.414,45.94125,-130.02061,1.005,1.2,OOAXAS1,0.054,2,0.65,1.0,EH,1.34,1.0,EH
311430,1501617,2021,2021-12-29 00:09:14.414,45.94125,-130.02061,1.005,1.2,OOAXCC1,0.054,2,0.60,1.0,HH,1.19,0.5,HH
311431,1501617,2021,2021-12-29 00:09:14.414,45.94125,-130.02061,1.005,1.2,OOAXEC1,0.054,2,0.86,1.0,EH,1.60,1.0,EH
311432,1501617,2021,2021-12-29 00:09:14.414,45.94125,-130.02061,1.005,1.2,OOAXID1,0.054,2,0.97,1.0,EH,1.64,1.0,EH

In [34]:
# Filter out rows where p_arrival_time < 0
print(f"Original filtered dataframe shape: {catalog_filtered.shape}")
print(f"Number of rows with p_arrival_time < 0: {(catalog_filtered['p_arrival_time'] < 0).sum()}")

# Create new dataframe excluding rows with p_arrival_time < 0
catalog_p_filtered = catalog_filtered[catalog_filtered['p_arrival_time'] >= 0].copy()

print(f"New dataframe shape after p_arrival_time filter: {catalog_p_filtered.shape}")
print(f"Rows removed: {catalog_filtered.shape[0] - catalog_p_filtered.shape[0]}")

# Check the range of p_arrival_time values
print(f"\nP arrival time range: {catalog_p_filtered['p_arrival_time'].min()} to {catalog_p_filtered['p_arrival_time'].max()}")
print(f"Number of valid P arrival times: {catalog_p_filtered['p_arrival_time'].notna().sum()}")

Original filtered dataframe shape: (301879, 16)
Number of rows with p_arrival_time < 0: 7259
New dataframe shape after p_arrival_time filter: (294620, 16)
Rows removed: 7259

P arrival time range: 0.0 to 6.44
Number of valid P arrival times: 294620

In [35]:
# Save the complete filtered dataframe to CSV
catalog_p_filtered.to_csv('../data/catalog_filtered.csv', index=False)

# Save only the first 100 rows to a separate CSV file
catalog_p_filtered.head(100).to_csv('../data/catalog_filtered_sample.csv', index=False)

print(f"Full dataset saved to '../data/catalog_filtered.csv'")
print(f"Sample of 100 rows saved to '../data/catalog_filtered_sample.csv'")
print(f"Full dataset size: {catalog_p_filtered.shape[0]} rows x {catalog_p_filtered.shape[1]} columns")
print(f"Sample dataset size: 100 rows x {catalog_p_filtered.shape[1]} columns")

Full dataset saved to '../data/catalog_filtered.csv'
Sample of 100 rows saved to '../data/catalog_filtered_sample.csv'
Full dataset size: 294620 rows x 16 columns
Sample dataset size: 100 rows x 16 columns